name: TDI

# Controls when the workflow will run

on:

  

  push:

    branches: [ "main" ]



  pull_request:

    types: [closed]

jobs:

  # This workflow contains a single job called "build"

  build:

    runs-on: ubuntu-latest

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access 

      - uses: actions/checkout@v3

      - name: creating a file

        run: echo file 2 created >file2.txt



      - name: displaying the contents

        run: cat file2.txt



      - run : |
          
          cp file1.txt file2.txt
          
          cat file2.txt



      - uses : actions/upload-artifact@v3

        with:

          name: my-artifact

          path: file2.txt
