name: Create New Branch

on:
  push:
    branches: [main]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create new branch
        run: git checkout -b new-branch
      - name: Push new branch
        uses: ad-m/github-push-action@master
        with:
          branch: new-branch
