name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        echo "hello world"

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifacts
        path: /path/to/artifacts/*
